'use strict'
// const a=10;
// const b=20;
// console.log(a+b);
//  console.log(20/10);
//  console.log(10*b);
//  const fristName='hi';
//  const lastName='hello';
//  console.log(fristName,lastName);
//  console.log(`${fristName} java `);
//  let x=10+5;
//  x+=10;
//  console.log(x);
//  let  a=5;
//  console.log(a**2);
// console.log(b<a);
// console.log(b>a);
// console.log(b>=20);
// let name$='hi';
// console.log(fristName+lastName);
// console.log(fristName,lastName);
// console.log(fristName+' '+lastName);
// let weight=78;
// let heigth=1.69;
// let bmi=(weight/heigth)**2;
// let weight1=92;
// let heigth1=1.95;
// let bmi1=(weight1/heigth1)**2;
// let a=bmi>bmi1;
// console.log(a);
// let weight=95;
// let heigth=1.88;
// let bmi=(weight/heigth)**2;
// let weight1=85;
// let heigth1=1.76;
// let bmi1=(weight1/heigth1)**2;
// let a=bmi>bmi1;
// console.log(a);
const a='nithin \n\ kumar';
console.log(a);
const b=`hi
hello`;
console.log(b);